In [37]:
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import pandas as pd

# Jobs In Demand

In [38]:
#the dataset for the given table is 

job=pd.read_csv('C:/Users/Acer/Job_analysis/new_csv_files/job_in_demand.csv')
job

,job_title_short,total_jobs,avg_salary,max_salary,min_salary,salary_rank,job_rank
0,Senior Data Scientist,2016,154050,890000,45000,1,5
1,Senior Data Engineer,2031,145867,425000,35000,2,4
2,Data Scientist,8584,135929,960000,27000,3,2
3,Data Engineer,6875,130267,525000,15000,4,3
4,Machine Learning Engineer,634,126786,325000,30000,5,8
5,Senior Data Analyst,1494,114104,425000,30000,6,6
6,Software Engineer,589,112778,375000,28000,7,9
7,Cloud Engineer,90,111268,280000,42000,8,10
8,Data Analyst,9756,93876,650000,25000,9,1
9,Business Analyst,1031,91071,387460,16500,10,7

In [39]:

job=job.sort_values('avg_salary',ascending=True)


fig=px.bar(
    job,
    x='avg_salary',
    y='job_title_short',
    orientation='h',
    color='total_jobs',
    hover_data=['min_salary','max_salary'],
    color_continuous_scale='teal'
)

fig.update_layout(
    xaxis_title='Average Salary ($)',
    yaxis_title='Job Role',
    plot_bgcolor='white',
    coloraxis_colorbar=dict(title='Total Jobs')
)



fig.show()

In [40]:
#Insights
#Senior data scientist have highest salary but the number of the job is less
# Data Analyst is the role which have the highest number of jobs
# Data Scientist are also in the great demand with the highest salary around 140k
#Business Analyst is the role which have the less jobs as well as less salary

# Remote vs Non Remote Salary

In [41]:
df=pd.read_csv('C:/Users/Acer/Job_analysis/new_csv_files/remote_vs_nonremote.csv')
df

,Job,Remote Pay,Onsite Pay,Difference,Prefer
0,Cloud Engineer,147111,105508,41603,Remote Better
1,Machine Learning Engineer,148670,125144,23527,Remote Better
2,Senior Data Scientist,163798,151633,12165,Remote Better
3,Software Engineer,122367,111235,11132,Remote Better
4,Data Scientist,144398,134307,10092,Remote Better
5,Business Analyst,97114,90197,6917,Remote Better
6,Senior Data Engineer,148245,145364,2881,Remote Better
7,Data Engineer,132364,129847,2517,Remote Better
8,Data Analyst,94770,93765,1005,Remote Better
9,Senior Data Analyst,113335,114229,-894,Onsite Better

In [42]:
df = df.sort_values('Prefer', ascending=False)
fig=px.bar(
    df,
    x='Job',
    y=['Remote Pay','Onsite Pay'],
    barmode='group',
    title='Remote vs Non-Remote Salary Comparison',
    color_discrete_map={
        'Remote Pay': '#2E86AB',    
        'Onsite Pay': '#E84855'    
    }
)

fig.update_layout(
    xaxis_title='Job Role',
    yaxis_title='Average Salary ($)',
    legend_title='Work Type',
    xaxis_tickangle=-45,
    plot_bgcolor='white',
    paper_bgcolor='white',
    
)
fig.show()

In [43]:
#Insights

#Cloud Engineer have the highest difference in Remote pay than any other
#Senior Data Scientist have the highest remote pay salary
#Business analyst have low remote pay as well as onsite pay
#Data analyst ,Engineer and Senior data analyst have the same number of the salary difference

# Hire Trend Month

In [44]:
trend=pd.read_csv('C:/Users/Acer/Job_analysis/new_csv_files/hire_trend_month.csv')
trend

     Periods  Total Jobs  AVG Salary
0   Jan 2023        2317      123641
1   Feb 2023        1983      122475
2   Mar 2023        2219      123045
3   Apr 2023        1863      121540
4   May 2023        1923      124010
5   Jun 2023        2318      124278
6   Jul 2023        2237      123414
7   Aug 2023        2098      125313
8   Sep 2023        1246      125680
9   Oct 2023        1313      124089
10  Nov 2023        1131      119822
11  Dec 2023        1363      120193

In [45]:
#so here we need the representation for the line chart hiring trend number of the jobs for the particular period

fig=px.line(
    trend,
    x='Periods',
    y='Total Jobs',
    title='Hiring Trend By Month',
    hover_data='Total Jobs',
    markers=True,
    line_shape='spline',           
    color_discrete_sequence=['#2E86AB']  
)

fig.update_layout(
    xaxis_title='Months',
    yaxis_title='Total Number of Jobs',
    
    
    xaxis_tickangle=-45
)

fig.show()

In [46]:
#Insights
#The number of the jobs are more in Jan month
#June the hiring get boom 
#September there is the sudden decrease in the hiring
#November the hiring get less

# Top Companies

In [47]:
top=pd.read_csv('C:/Users/Acer/Job_analysis/new_csv_files/top_companies.csv')
top

,Job Name,Company Name,AVG Salary,Total Jobs,Rank by Salary
0,Data Scientist,"East River Electric Power Cooperative, Inc.",537000,2,2
1,Data Scientist,Linquest Corporation,375000,3,3
2,Data Analyst,Illuminate Mission Solutions,375000,2,3
3,Data Engineer,Durlston Partners,371000,5,4
4,Senior Data Scientist,Algo Capital Group,362500,4,4
5,Data Scientist,Zoox.com,350000,2,4
6,Data Engineer,Algo Capital Group,343750,4,6
7,Data Scientist,Demandbase,342333,3,5
8,Data Scientist,Algo Capital Group,330000,5,7
9,Data Engineer,Engtal,325000,2,7
10,Senior Data Scientist,Source Technology,315000,2,6
11,Senior Data Scientist,Phenom Labs,300000,2,9
12,Data Analyst,Anthropic,295000,2,5
13,Senior Data Scientist,Glocomms,282500,3,10
14,Senior Data Engineer,Capital Markets Recruitment,270000,2,5
15,Senior Data Engineer,Engtal,261429,7,7
16,Machine Learning Engineer,TikTok,253000,2,4
17,Senior Data Analyst,General Dynamics,250000,2,4
18,Senior Data Analyst,GradBay,240000,2,5
19,Machine Learning Engineer,Acceler8 Talent,237000,5,7
20,Software Engineer,TikTok,236542,3,9
21,Machine Learning Engineer,MongoDB,235500,2,8
22,Machine Learning Engineer,Capital One,228750,2,9
23,Business Analyst,Multicoin Capital,200000,2,4
24,Cloud Engineer,MongoDB,194667,3,5
25,Senior Data Analyst,U.S. Department of the Treasury,193048,2,8
26,Senior Data Analyst,Deel,189000,2,9
27,Senior Data Analyst,Etsy,186250,2,10
28,Business Analyst,Block,171000,3,7
29,Business Analyst,Nextracker Inc.,160000,2,9
30,Cloud Engineer,"The Travelers Companies, Inc.",145000,5,7

In [48]:
#so here we need the analysis for the job name and how nmany average salary does the particular company is offer

fig=px.bar(
    top,
    x='AVG Salary',
    y='Company Name',
    orientation='h',
    title='Top Paying Companies By Role',
    color='Job Name',
    hover_data=['Total Jobs']
)

fig.update_layout(
    xaxis_title='Average Salary ($)',
    yaxis_title='Company',
    margin=dict(l=250,r=50),       
    height=600,   
   
    legend_title='Job Roles'
)

fig.show()

In [49]:
# Algo Capital Group is the company which hire Data Scientist(0.3M), Data Engineer with (0.3-0.7M) and Senior Data Scientist with (0.7-2M)
# The avg salary of cloud engineer in teh travalelers Companies Inc is less as compared to MongoDB
# 3 Companies hire Business Analyst with very less amount of salary

# Salary Percent

In [50]:
percent=pd.read_csv('C:/Users/Acer/Job_analysis/new_csv_files/salary_percent.csv')
percent

,job_title_short,p25,p50,p75,p90,avg_salary,total_jobs
0,Senior Data Scientist,125000,155000,173000,200000,154050,1686
1,Senior Data Engineer,125000,147500,166761,181860,145867,1594
2,Data Scientist,100000,127500,158858,200000,135929,5926
3,Data Engineer,100000,125000,147500,175000,130267,4509
4,Senior Data Analyst,92500,111175,125000,150000,114104,1132
5,Machine Learning Engineer,80850,106000,166000,190000,126786,573
6,Software Engineer,79200,99150,147500,184500,112778,469
7,Data Analyst,70000,90000,111175,132620,93876,5463
8,Cloud Engineer,79200,90000,136000,196500,111268,65
9,Business Analyst,71000,85000,105000,130000,91071,617

In [51]:
#so there we need to make the analysis for the job_title_short where the salary is percent 25 percent 50 percent 75 percent 90 earn more

fig = px.bar(
    percent,
    x='job_title_short',
    y=['p25', 'p50', 'p75', 'p90'],
    barmode='group',
    title='Salary Percentile by Job Role',
    color_discrete_sequence=['#2E86AB', '#A23B72', '#F18F01', '#C73E1D']
)

fig.update_layout(
    xaxis_title='Job Role',
    yaxis_title='Salary ($)',
   
    xaxis_tickangle=-45,
    legend_title='Percentile'
)

fig.show()

In [52]:
# Senior roles (Data Scientist, Data Engineer) pay the most P90: $200k+
# ML Engineer has the biggest salary gap with experience matters most here
# Data Analyst is the most stable but lowest paying role
# Senior earn more in most of the jobs

# Skill Type Analysis

In [53]:
tp=pd.read_csv('C:/Users/Acer/Job_analysis/new_csv_files/skill_type_analysis.csv')
tp

      skill_type  total_jobs  avg_salary
0      libraries       17685      139470
1          cloud       17607      133229
2      databases        4831      129363
3    programming       47552      129193
4  webframeworks        1321      128969
5          other        6984      128585
6             os        1431      122546
7          async        1096      120882
8           sync         300      119533
9  analyst_tools       20272      108550

In [54]:
tp=tp.sort_values('avg_salary',ascending=True)

fig = px.bar(
    tp,
    x='avg_salary',
    y='skill_type',
    orientation='h',
   
    color='total_jobs',
    title='Skill Type — Demand vs Salary',
    color_continuous_scale='teal',
    hover_data=['total_jobs']
)

fig.update_layout(
    xaxis_title='Average Salary ($)',
    yaxis_title='Skill Type',
    coloraxis_colorbar=dict(title='Total Jobs'),
     
)
fig.update_traces(
    textposition='outside'  
)

fig.show()

In [55]:
# Libraries (TensorFlow, PyTorch) pay the most ($139k) AI/ML skills are premium
# Cloud skills (AWS, Azure, GCP) are close second ($133k) with high demand
# Analyst tools (Excel, Tableau) pay the least ($108k) despite decent demand
# Programming has highest demand (47k jobs) but average salary.

# Top Paying Skills

In [56]:
df=pd.read_csv('C:/Users/Acer/Job_analysis/new_csv_files/top_paying_skills.csv')
df

          skills  avg_salary
0            svn      400000
1       solidity      179000
2      couchbase      160515
3      datarobot      155486
4         golang      155000
5          mxnet      149000
6          dplyr      147633
7         vmware      147500
8      terraform      146734
9         twilio      138500
10        gitlab      134126
11         kafka      129999
12        puppet      129820
13         keras      127013
14       pytorch      125226
15          perl      124686
16       ansible      124370
17  hugging face      123950
18    tensorflow      120647
19     cassandra      118407
20        notion      118092
21     atlassian      117966
22     bitbucket      116712
23       airflow      116387
24         scala      115480

In [57]:
df=df.sort_values('avg_salary',ascending=True)

fig = px.bar(
    df,
    x='avg_salary',
    y='skills',
    orientation='h',
    color='avg_salary',
    color_continuous_scale='teal',
    title='Top Paying Skills',
)

fig.update_layout(
    xaxis_title='Average Salary ($)',
    yaxis_title='Skills',
    coloraxis_colorbar=dict(title='Avg Salary') ,
    height=600,
    margin=dict(l=80)  
)


fig.show()

In [58]:
# SVN ($400k) and Solidity ($179k) pay the most — niche/specialized skills command premium salaries
# Blockchain (Solidity) and DevOps (Terraform, Puppet) skills are highly valued
# Most top paying skills are specialized tools — not common ones like SQL or Python
# Learning niche skills can significantly boost salary even without senior title